// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-yY3DWVHoWQTUmZcVQnyJEJ7LXf7gcM',
    appId: '1:68249087854:web:acbd2c076a1bbd9559db7f',
    messagingSenderId: '68249087854',
    projectId: 'chatapp-61675',
    authDomain: 'chatapp-61675.firebaseapp.com',
    storageBucket: 'chatapp-61675.firebasestorage.app',
    measurementId: 'G-HF7Q2JBFJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKRoPUR8nHY8yU9yFclP7F9X-n3SgeNNE',
    appId: '1:68249087854:android:78fbd52670f4e9eb59db7f',
    messagingSenderId: '68249087854',
    projectId: 'chatapp-61675',
    storageBucket: 'chatapp-61675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qORz1FqkGp3GIUmfeV_6yt7R2j-abME',
    appId: '1:68249087854:ios:0ac29678a37ed7e459db7f',
    messagingSenderId: '68249087854',
    projectId: 'chatapp-61675',
    storageBucket: 'chatapp-61675.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3qORz1FqkGp3GIUmfeV_6yt7R2j-abME',
    appId: '1:68249087854:ios:0ac29678a37ed7e459db7f',
    messagingSenderId: '68249087854',
    projectId: 'chatapp-61675',
    storageBucket: 'chatapp-61675.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-yY3DWVHoWQTUmZcVQnyJEJ7LXf7gcM',
    appId: '1:68249087854:web:4684b3552cc51bca59db7f',
    messagingSenderId: '68249087854',
    projectId: 'chatapp-61675',
    authDomain: 'chatapp-61675.firebaseapp.com',
    storageBucket: 'chatapp-61675.firebasestorage.app',
    measurementId: 'G-VQ7XC2K3BY',
  );
}
